/*
 * Automatically generated C config: don't edit
 * Linux kernel version: 2.6.9-ac11
 * Sun Jan 23 12:49:06 2011
 */
#define AUTOCONF_INCLUDED
#define CONFIG_X86_64 1
#define CONFIG_64BIT 1
#define CONFIG_X86 1
#define CONFIG_MMU 1
#define CONFIG_RWSEM_GENERIC_SPINLOCK 1
#define CONFIG_X86_CMPXCHG 1
#define CONFIG_EARLY_PRINTK 1
#define CONFIG_HPET_TIMER 1
#define CONFIG_HPET_EMULATE_RTC 1
#define CONFIG_GENERIC_ISA_DMA 1
#define CONFIG_GENERIC_IOMAP 1

/*
 * Code maturity level options
 */
#define CONFIG_EXPERIMENTAL 1
#define CONFIG_CLEAN_COMPILE 1
#define CONFIG_BROKEN_ON_SMP 1

/*
 * General setup
 */
#define CONFIG_LOCALVERSION ""
#define CONFIG_SWAP 1
#define CONFIG_SYSVIPC 1
#define CONFIG_POSIX_MQUEUE 1
#define CONFIG_BSD_PROCESS_ACCT 1
#undef CONFIG_BSD_PROCESS_ACCT_V3
#define CONFIG_SYSCTL 1
#define CONFIG_AUDIT 1
#define CONFIG_AUDITSYSCALL 1
#define CONFIG_LOG_BUF_SHIFT 17
#define CONFIG_HOTPLUG 1
#undef CONFIG_IKCONFIG
#undef CONFIG_EMBEDDED
#define CONFIG_KALLSYMS 1
#undef CONFIG_KALLSYMS_ALL
#define CONFIG_KALLSYMS_EXTRA_PASS 1
#define CONFIG_FUTEX 1
#define CONFIG_EPOLL 1
#define CONFIG_IOSCHED_NOOP 1
#define CONFIG_IOSCHED_AS 1
#define CONFIG_IOSCHED_DEADLINE 1
#define CONFIG_IOSCHED_CFQ 1
#define CONFIG_CC_OPTIMIZE_FOR_SIZE 1
#define CONFIG_SHMEM 1
#undef CONFIG_TINY_SHMEM

/*
 * Loadable module support
 */
#define CONFIG_MODULES 1
#define CONFIG_MODULE_UNLOAD 1
#undef CONFIG_MODULE_FORCE_UNLOAD
#define CONFIG_OBSOLETE_MODPARM 1
#define CONFIG_MODVERSIONS 1
#define CONFIG_MODULE_SIG 1
#undef CONFIG_MODULE_SIG_FORCE
#define CONFIG_KMOD 1

/*
 * Processor type and features
 */
#undef CONFIG_MK8
#undef CONFIG_MPSC
#define CONFIG_GENERIC_CPU 1
#define CONFIG_X86_L1_CACHE_BYTES 128
#define CONFIG_X86_L1_CACHE_SHIFT 7
#define CONFIG_X86_TSC 1
#define CONFIG_X86_GOOD_APIC 1
#define CONFIG_MICROCODE_MODULE 1
#define CONFIG_X86_MSR 1
#define CONFIG_X86_CPUID 1
#define CONFIG_X86_IO_APIC 1
#define CONFIG_X86_LOCAL_APIC 1
#define CONFIG_MTRR 1
#undef CONFIG_SMP
#undef CONFIG_PREEMPT
#define CONFIG_GART_IOMMU 1
#define CONFIG_SWIOTLB 1
#define CONFIG_X86_MCE 1

/*
 * Power management options
 */
#define CONFIG_PM 1
#undef CONFIG_PM_DEBUG
#undef CONFIG_SOFTWARE_SUSPEND

/*
 * ACPI (Advanced Configuration and Power Interface) Support
 */
#define CONFIG_ACPI 1
#define CONFIG_ACPI_BOOT 1
#define CONFIG_ACPI_INTERPRETER 1
#define CONFIG_ACPI_SLEEP 1
#define CONFIG_ACPI_SLEEP_PROC_FS 1
#define CONFIG_ACPI_AC_MODULE 1
#define CONFIG_ACPI_BATTERY_MODULE 1
#define CONFIG_ACPI_BUTTON_MODULE 1
#define CONFIG_ACPI_FAN 1
#define CONFIG_ACPI_PROCESSOR 1
#define CONFIG_ACPI_THERMAL 1
#define CONFIG_ACPI_ASUS_MODULE 1
#define CONFIG_ACPI_TOSHIBA_MODULE 1
#define CONFIG_ACPI_BLACKLIST_YEAR 2001
#undef CONFIG_ACPI_DEBUG
#define CONFIG_ACPI_BUS 1
#define CONFIG_ACPI_EC 1
#define CONFIG_ACPI_POWER 1
#define CONFIG_ACPI_PCI 1
#define CONFIG_ACPI_SYSTEM 1

/*
 * CPU Frequency scaling
 */
#define CONFIG_CPU_FREQ 1
#undef CONFIG_CPU_FREQ_PROC_INTF
#undef CONFIG_CPU_FREQ_DEFAULT_GOV_PERFORMANCE
#define CONFIG_CPU_FREQ_DEFAULT_GOV_USERSPACE 1
#define CONFIG_CPU_FREQ_GOV_PERFORMANCE 1
#define CONFIG_CPU_FREQ_GOV_POWERSAVE_MODULE 1
#define CONFIG_CPU_FREQ_GOV_USERSPACE 1
#define CONFIG_CPU_FREQ_GOV_ONDEMAND_MODULE 1
#undef CONFIG_CPU_FREQ_24_API
#define CONFIG_CPU_FREQ_TABLE 1

/*
 * CPUFreq processor drivers
 */
#define CONFIG_X86_POWERNOW_K8 1
#define CONFIG_X86_POWERNOW_K8_ACPI 1
#undef CONFIG_X86_SPEEDSTEP_CENTRINO
#define CONFIG_X86_ACPI_CPUFREQ 1
#undef CONFIG_X86_ACPI_CPUFREQ_PROC_INTF

/*
 * Bus options (PCI etc.)
 */
#define CONFIG_PCI 1
#define CONFIG_PCI_DIRECT 1
#define CONFIG_PCI_MMCONFIG 1
#undef CONFIG_UNORDERED_IO
#define CONFIG_PCI_MSI 1
#define CONFIG_PCI_LEGACY_PROC 1
#undef CONFIG_PCI_NAMES

/*
 * PCMCIA/CardBus support
 */
#define CONFIG_PCMCIA_MODULE 1
#undef CONFIG_PCMCIA_DEBUG
#define CONFIG_YENTA_MODULE 1
#define CONFIG_CARDBUS 1
#define CONFIG_PD6729_MODULE 1
#undef CONFIG_I82092
#define CONFIG_TCIC_MODULE 1

/*
 * PCI Hotplug Support
 */
#define CONFIG_HOTPLUG_PCI 1
#undef CONFIG_HOTPLUG_PCI_FAKE
#define CONFIG_HOTPLUG_PCI_ACPI_MODULE 1
#define CONFIG_HOTPLUG_PCI_ACPI_IBM_MODULE 1
#undef CONFIG_HOTPLUG_PCI_CPCI
#define CONFIG_HOTPLUG_PCI_PCIE_MODULE 1
#undef CONFIG_HOTPLUG_PCI_PCIE_POLL_EVENT_MODE
#define CONFIG_HOTPLUG_PCI_SHPC_MODULE 1
#undef CONFIG_HOTPLUG_PCI_SHPC_POLL_EVENT_MODE

/*
 * Executable file formats / Emulations
 */
#define CONFIG_BINFMT_ELF 1
#define CONFIG_BINFMT_MISC 1
#define CONFIG_IA32_EMULATION 1
#undef CONFIG_IA32_AOUT
#define CONFIG_COMPAT 1
#define CONFIG_SYSVIPC_COMPAT 1
#define CONFIG_UID16 1
#define CONFIG_KEXEC 1

/*
 * Device Drivers
 */

/*
 * Generic Driver Options
 */
#define CONFIG_STANDALONE 1
#define CONFIG_PREVENT_FIRMWARE_BUILD 1
#define CONFIG_FW_LOADER 1
#undef CONFIG_DEBUG_DRIVER

/*
 * Memory Technology Devices (MTD)
 */
#define CONFIG_MTD_MODULE 1
#undef CONFIG_MTD_DEBUG
#define CONFIG_MTD_PARTITIONS 1
#define CONFIG_MTD_CONCAT_MODULE 1
#define CONFIG_MTD_REDBOOT_PARTS_MODULE 1
#undef CONFIG_MTD_REDBOOT_PARTS_UNALLOCATED
#undef CONFIG_MTD_REDBOOT_PARTS_READONLY
#define CONFIG_MTD_CMDLINE_PARTS 1

/*
 * User Modules And Translation Layers
 */
#define CONFIG_MTD_CHAR_MODULE 1
#define CONFIG_MTD_BLOCK_MODULE 1
#define CONFIG_MTD_BLOCK_RO_MODULE 1
#define CONFIG_FTL_MODULE 1
#define CONFIG_NFTL_MODULE 1
#define CONFIG_NFTL_RW 1
#undef CONFIG_INFTL

/*
 * RAM/ROM/Flash chip drivers
 */
#define CONFIG_MTD_CFI_MODULE 1
#define CONFIG_MTD_JEDECPROBE_MODULE 1
#define CONFIG_MTD_GEN_PROBE_MODULE 1
#undef CONFIG_MTD_CFI_ADV_OPTIONS
#define CONFIG_MTD_MAP_BANK_WIDTH_1 1
#define CONFIG_MTD_MAP_BANK_WIDTH_2 1
#define CONFIG_MTD_MAP_BANK_WIDTH_4 1
#undef CONFIG_MTD_MAP_BANK_WIDTH_8
#undef CONFIG_MTD_MAP_BANK_WIDTH_16
#undef CONFIG_MTD_MAP_BANK_WIDTH_32
#define CONFIG_MTD_CFI_I1 1
#define CONFIG_MTD_CFI_I2 1
#undef CONFIG_MTD_CFI_I4
#undef CONFIG_MTD_CFI_I8
#define CONFIG_MTD_CFI_INTELEXT_MODULE 1
#define CONFIG_MTD_CFI_AMDSTD_MODULE 1
#define CONFIG_MTD_CFI_AMDSTD_RETRY 3
#define CONFIG_MTD_CFI_STAA_MODULE 1
#define CONFIG_MTD_CFI_UTIL_MODULE 1
#define CONFIG_MTD_RAM_MODULE 1
#define CONFIG_MTD_ROM_MODULE 1
#define CONFIG_MTD_ABSENT_MODULE 1

/*
 * Mapping drivers for chip access
 */
#undef CONFIG_MTD_COMPLEX_MAPPINGS
#undef CONFIG_MTD_PHYSMAP
#undef CONFIG_MTD_PNC2000
#define CONFIG_MTD_SC520CDP_MODULE 1
#define CONFIG_MTD_NETSC520_MODULE 1
#define CONFIG_MTD_SCx200_DOCFLASH_MODULE 1
#undef CONFIG_MTD_AMD76XROM
#undef CONFIG_MTD_SCB2_FLASH
#undef CONFIG_MTD_NETtel
#undef CONFIG_MTD_DILNETPC
#undef CONFIG_MTD_L440GX

/*
 * Self-contained MTD device drivers
 */
#undef CONFIG_MTD_PMC551
#undef CONFIG_MTD_SLRAM
#undef CONFIG_MTD_PHRAM
#define CONFIG_MTD_MTDRAM_MODULE 1
#define CONFIG_MTDRAM_TOTAL_SIZE 4096
#define CONFIG_MTDRAM_ERASE_SIZE 128
#undef CONFIG_MTD_BLKMTD

/*
 * Disk-On-Chip Device Drivers
 */
#undef CONFIG_MTD_DOC2000
#undef CONFIG_MTD_DOC2001
#undef CONFIG_MTD_DOC2001PLUS

/*
 * NAND Flash Device Drivers
 */
#define CONFIG_MTD_NAND_MODULE 1
#undef CONFIG_MTD_NAND_VERIFY_WRITE
#define CONFIG_MTD_NAND_IDS_MODULE 1
#undef CONFIG_MTD_NAND_DISKONCHIP

/*
 * Parallel port support
 */
#define CONFIG_PARPORT_MODULE 1
#define CONFIG_PARPORT_PC_MODULE 1
#define CONFIG_PARPORT_PC_CML1_MODULE 1
#define CONFIG_PARPORT_SERIAL_MODULE 1
#undef CONFIG_PARPORT_PC_FIFO
#undef CONFIG_PARPORT_PC_SUPERIO
#define CONFIG_PARPORT_PC_PCMCIA_MODULE 1
#undef CONFIG_PARPORT_OTHER
#define CONFIG_PARPORT_1284 1

/*
 * Plug and Play support
 */

/*
 * Block devices
 */
#define CONFIG_BLK_DEV_FD_MODULE 1
#undef CONFIG_PARIDE
#define CONFIG_BLK_CPQ_DA_MODULE 1
#define CONFIG_BLK_CPQ_CISS_DA_MODULE 1
#define CONFIG_CISS_SCSI_TAPE 1
#define CONFIG_BLK_DEV_DAC960_MODULE 1
#undef CONFIG_BLK_DEV_UMEM
#define CONFIG_BLK_DEV_LOOP_MODULE 1
#define CONFIG_BLK_DEV_CRYPTOLOOP_MODULE 1
#define CONFIG_BLK_DEV_NBD_MODULE 1
#define CONFIG_BLK_DEV_SX8_MODULE 1
#undef CONFIG_BLK_DEV_UB
#define CONFIG_BLK_DEV_RAM 1
#define CONFIG_BLK_DEV_RAM_SIZE 16384
#define CONFIG_BLK_DEV_INITRD 1
#define CONFIG_LBD 1
#define CONFIG_DISKDUMP_MODULE 1

/*
 * ATA/ATAPI/MFM/RLL support
 */
#define CONFIG_IDE 1
#define CONFIG_BLK_DEV_IDE 1

/*
 * Please see Documentation/ide.txt for help/info on IDE drives
 */
#undef CONFIG_BLK_DEV_IDE_SATA
#undef CONFIG_BLK_DEV_HD_IDE
#define CONFIG_BLK_DEV_IDEDISK 1
#define CONFIG_IDEDISK_MULTI_MODE 1
#define CONFIG_BLK_DEV_IDECS_MODULE 1
#define CONFIG_BLK_DEV_DELKIN_MODULE 1
#define CONFIG_BLK_DEV_IDECD 1
#undef CONFIG_BLK_DEV_IDETAPE
#define CONFIG_BLK_DEV_IDEFLOPPY 1
#define CONFIG_BLK_DEV_IDESCSI_MODULE 1
#undef CONFIG_IDE_TASK_IOCTL
#undef CONFIG_IDE_TASKFILE_IO

/*
 * IDE chipset support/bugfixes
 */
#define CONFIG_IDE_GENERIC 1
#undef CONFIG_BLK_DEV_CMD640
#define CONFIG_BLK_DEV_IDEPCI 1
#define CONFIG_IDEPCI_SHARE_IRQ 1
#undef CONFIG_BLK_DEV_OFFBOARD
#define CONFIG_BLK_DEV_GENERIC 1
#undef CONFIG_BLK_DEV_OPTI621
#define CONFIG_BLK_DEV_RZ1000 1
#define CONFIG_BLK_DEV_IDEDMA_PCI 1
#undef CONFIG_BLK_DEV_IDEDMA_FORCED
#define CONFIG_IDEDMA_PCI_AUTO 1
#undef CONFIG_IDEDMA_ONLYDISK
#define CONFIG_BLK_DEV_AEC62XX 1
#define CONFIG_BLK_DEV_ALI15X3 1
#undef CONFIG_WDC_ALI15X3
#define CONFIG_BLK_DEV_AMD74XX 1
#define CONFIG_BLK_DEV_ATIIXP 1
#define CONFIG_BLK_DEV_CMD64X 1
#define CONFIG_BLK_DEV_TRIFLEX 1
#define CONFIG_BLK_DEV_CY82C693 1
#define CONFIG_BLK_DEV_CS5520 1
#define CONFIG_BLK_DEV_CS5530 1
#define CONFIG_BLK_DEV_HPT34X 1
#undef CONFIG_HPT34X_AUTODMA
#define CONFIG_BLK_DEV_HPT366 1
#undef CONFIG_BLK_DEV_SC1200
#define CONFIG_BLK_DEV_PIIX 1
#define CONFIG_BLK_DEV_IT8212 1
#undef CONFIG_BLK_DEV_NS87415
#define CONFIG_BLK_DEV_PDC202XX_OLD 1
#undef CONFIG_PDC202XX_BURST
#define CONFIG_BLK_DEV_PDC202XX_NEW 1
#define CONFIG_PDC202XX_FORCE 1
#define CONFIG_BLK_DEV_SVWKS 1
#define CONFIG_BLK_DEV_SIIMAGE 1
#define CONFIG_BLK_DEV_SIS5513 1
#define CONFIG_BLK_DEV_SLC90E66 1
#undef CONFIG_BLK_DEV_TRM290
#define CONFIG_BLK_DEV_VIA82CXXX 1
#undef CONFIG_IDE_ARM
#define CONFIG_BLK_DEV_IDEDMA 1
#undef CONFIG_IDEDMA_IVB
#define CONFIG_IDEDMA_AUTO 1
#undef CONFIG_BLK_DEV_HD

/*
 * SCSI device support
 */
#define CONFIG_SCSI_MODULE 1
#define CONFIG_SCSI_PROC_FS 1

/*
 * SCSI support type (disk, tape, CD-ROM)
 */
#define CONFIG_BLK_DEV_SD_MODULE 1
#define CONFIG_SCSI_DUMP_MODULE 1
#define CONFIG_CHR_DEV_ST_MODULE 1
#define CONFIG_CHR_DEV_OSST_MODULE 1
#define CONFIG_BLK_DEV_SR_MODULE 1
#define CONFIG_BLK_DEV_SR_VENDOR 1
#define CONFIG_CHR_DEV_SG_MODULE 1

/*
 * Some SCSI devices (e.g. CD jukebox) support multiple LUNs
 */
#undef CONFIG_SCSI_MULTI_LUN
#define CONFIG_SCSI_CONSTANTS 1
#define CONFIG_SCSI_LOGGING 1

/*
 * SCSI Transport Attributes
 */
#define CONFIG_SCSI_SPI_ATTRS_MODULE 1
#define CONFIG_SCSI_FC_ATTRS_MODULE 1

/*
 * SCSI low-level drivers
 */
#define CONFIG_BLK_DEV_3W_XXXX_RAID_MODULE 1
#define CONFIG_SCSI_3W_9XXX_MODULE 1
#define CONFIG_SCSI_ACARD_MODULE 1
#define CONFIG_SCSI_AACRAID_MODULE 1
#define CONFIG_SCSI_AIC7XXX_MODULE 1
#define CONFIG_AIC7XXX_CMDS_PER_DEVICE 4
#define CONFIG_AIC7XXX_RESET_DELAY_MS 15000
#undef CONFIG_AIC7XXX_DEBUG_ENABLE
#define CONFIG_AIC7XXX_DEBUG_MASK 0
#undef CONFIG_AIC7XXX_REG_PRETTY_PRINT
#define CONFIG_SCSI_AIC7XXX_OLD_MODULE 1
#define CONFIG_SCSI_AIC79XX_MODULE 1
#define CONFIG_AIC79XX_CMDS_PER_DEVICE 4
#define CONFIG_AIC79XX_RESET_DELAY_MS 15000
#undef CONFIG_AIC79XX_ENABLE_RD_STRM
#undef CONFIG_AIC79XX_DEBUG_ENABLE
#define CONFIG_AIC79XX_DEBUG_MASK 0
#undef CONFIG_AIC79XX_REG_PRETTY_PRINT
#define CONFIG_MEGARAID_NEWGEN 1
#define CONFIG_MEGARAID_MM_MODULE 1
#define CONFIG_MEGARAID_MAILBOX_MODULE 1
#define CONFIG_SCSI_SATA 1
#define CONFIG_SCSI_SATA_AHCI_MODULE 1
#define CONFIG_SCSI_SATA_SVW_MODULE 1
#define CONFIG_SCSI_ATA_PIIX_MODULE 1
#define CONFIG_SCSI_SATA_NV_MODULE 1
#define CONFIG_SCSI_SATA_PROMISE_MODULE 1
#define CONFIG_SCSI_SATA_SX4_MODULE 1
#define CONFIG_SCSI_SATA_SIL_MODULE 1
#define CONFIG_SCSI_SATA_SIS_MODULE 1
#define CONFIG_SCSI_SATA_VIA_MODULE 1
#define CONFIG_SCSI_SATA_VITESSE_MODULE 1
#undef CONFIG_SCSI_BUSLOGIC
#undef CONFIG_SCSI_DMX3191D
#undef CONFIG_SCSI_EATA
#undef CONFIG_SCSI_EATA_PIO
#define CONFIG_SCSI_LPFC_MODULE 1
#undef CONFIG_SCSI_FUTURE_DOMAIN
#define CONFIG_SCSI_GDTH_MODULE 1
#define CONFIG_SCSI_IPS_MODULE 1
#define CONFIG_SCSI_INITIO_MODULE 1
#undef CONFIG_SCSI_INIA100
#define CONFIG_SCSI_PPA_MODULE 1
#define CONFIG_SCSI_IMM_MODULE 1
#undef CONFIG_SCSI_IZIP_EPP16
#undef CONFIG_SCSI_IZIP_SLOW_CTR
#define CONFIG_SCSI_SYM53C8XX_2_MODULE 1
#define CONFIG_SCSI_SYM53C8XX_DMA_ADDRESSING_MODE 1
#define CONFIG_SCSI_SYM53C8XX_DEFAULT_TAGS 16
#define CONFIG_SCSI_SYM53C8XX_MAX_TAGS 64
#undef CONFIG_SCSI_SYM53C8XX_IOMAPPED
#undef CONFIG_SCSI_IPR
#undef CONFIG_SCSI_QLOGIC_ISP
#undef CONFIG_SCSI_QLOGIC_FC
#define CONFIG_SCSI_QLOGIC_1280_MODULE 1
#define CONFIG_SCSI_QLA2XXX_MODULE 1
#define CONFIG_SCSI_QLA21XX_MODULE 1
#define CONFIG_SCSI_QLA22XX_MODULE 1
#define CONFIG_SCSI_QLA2300_MODULE 1
#define CONFIG_SCSI_QLA2322_MODULE 1
#define CONFIG_SCSI_QLA6312_MODULE 1
#define CONFIG_SCSI_QLA6322_MODULE 1
#undef CONFIG_SCSI_DC395x
#undef CONFIG_SCSI_DC390T
#undef CONFIG_SCSI_DEBUG

/*
 * PCMCIA SCSI adapter support
 */
#undef CONFIG_PCMCIA_FDOMAIN
#undef CONFIG_PCMCIA_QLOGIC
#undef CONFIG_PCMCIA_SYM53C500

/*
 * Multi-device support (RAID and LVM)
 */
#define CONFIG_MD 1
#define CONFIG_BLK_DEV_MD 1
#define CONFIG_MD_LINEAR_MODULE 1
#define CONFIG_MD_RAID0_MODULE 1
#define CONFIG_MD_RAID1_MODULE 1
#define CONFIG_MD_RAID10_MODULE 1
#define CONFIG_MD_RAID5_MODULE 1
#define CONFIG_MD_RAID6_MODULE 1
#define CONFIG_MD_MULTIPATH_MODULE 1
#define CONFIG_BLK_DEV_DM_MODULE 1
#define CONFIG_DM_CRYPT_MODULE 1
#define CONFIG_DM_SNAPSHOT_MODULE 1
#define CONFIG_DM_MIRROR_MODULE 1
#define CONFIG_DM_ZERO_MODULE 1

/*
 * Fusion MPT device support
 */
#define CONFIG_FUSION_MODULE 1
#define CONFIG_FUSION_MAX_SGE 40
#define CONFIG_FUSION_CTL_MODULE 1
#define CONFIG_FUSION_LAN_MODULE 1

/*
 * IEEE 1394 (FireWire) support
 */
#undef CONFIG_IEEE1394

/*
 * I2O device support
 */
#define CONFIG_I2O_MODULE 1
#define CONFIG_I2O_CONFIG_MODULE 1
#define CONFIG_I2O_BLOCK_MODULE 1
#define CONFIG_I2O_SCSI_MODULE 1
#define CONFIG_I2O_PROC_MODULE 1

/*
 * Networking support
 */
#define CONFIG_NET 1

/*
 * Networking options
 */
#define CONFIG_PACKET 1
#define CONFIG_PACKET_MMAP 1
#define CONFIG_NETLINK_DEV 1
#define CONFIG_UNIX 1
#define CONFIG_NET_KEY_MODULE 1
#define CONFIG_INET 1
#define CONFIG_IP_MULTICAST 1
#define CONFIG_IP_ADVANCED_ROUTER 1
#define CONFIG_IP_MULTIPLE_TABLES 1
#define CONFIG_IP_ROUTE_FWMARK 1
#define CONFIG_IP_ROUTE_MULTIPATH 1
#define CONFIG_IP_ROUTE_VERBOSE 1
#undef CONFIG_IP_PNP
#define CONFIG_NET_IPIP_MODULE 1
#define CONFIG_NET_IPGRE_MODULE 1
#define CONFIG_NET_IPGRE_BROADCAST 1
#define CONFIG_IP_MROUTE 1
#define CONFIG_IP_PIMSM_V1 1
#define CONFIG_IP_PIMSM_V2 1
#undef CONFIG_ARPD
#define CONFIG_SYN_COOKIES 1
#define CONFIG_INET_AH_MODULE 1
#define CONFIG_INET_ESP_MODULE 1
#define CONFIG_INET_IPCOMP_MODULE 1
#define CONFIG_INET_TUNNEL_MODULE 1

/*
 * IP: Virtual Server Configuration
 */
#define CONFIG_IP_VS_MODULE 1
#undef CONFIG_IP_VS_DEBUG
#define CONFIG_IP_VS_TAB_BITS 12

/*
 * IPVS transport protocol load balancing support
 */
#define CONFIG_IP_VS_PROTO_TCP 1
#define CONFIG_IP_VS_PROTO_UDP 1
#define CONFIG_IP_VS_PROTO_ESP 1
#define CONFIG_IP_VS_PROTO_AH 1

/*
 * IPVS scheduler
 */
#define CONFIG_IP_VS_RR_MODULE 1
#define CONFIG_IP_VS_WRR_MODULE 1
#define CONFIG_IP_VS_LC_MODULE 1
#define CONFIG_IP_VS_WLC_MODULE 1
#define CONFIG_IP_VS_LBLC_MODULE 1
#define CONFIG_IP_VS_LBLCR_MODULE 1
#define CONFIG_IP_VS_DH_MODULE 1
#define CONFIG_IP_VS_SH_MODULE 1
#define CONFIG_IP_VS_SED_MODULE 1
#define CONFIG_IP_VS_NQ_MODULE 1

/*
 * IPVS application helper
 */
#define CONFIG_IP_VS_FTP_MODULE 1
#define CONFIG_IPV6_MODULE 1
#define CONFIG_IPV6_PRIVACY 1
#define CONFIG_INET6_AH_MODULE 1
#define CONFIG_INET6_ESP_MODULE 1
#define CONFIG_INET6_IPCOMP_MODULE 1
#define CONFIG_INET6_TUNNEL_MODULE 1
#define CONFIG_IPV6_TUNNEL_MODULE 1
#define CONFIG_NETFILTER 1
#undef CONFIG_NETFILTER_DEBUG
#define CONFIG_BRIDGE_NETFILTER 1

/*
 * IP: Netfilter Configuration
 */
#define CONFIG_IP_NF_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_CT_ACCT 1
#define CONFIG_IP_NF_CT_PROTO_SCTP_MODULE 1
#define CONFIG_IP_NF_FTP_MODULE 1
#define CONFIG_IP_NF_IRC_MODULE 1
#define CONFIG_IP_NF_TFTP_MODULE 1
#define CONFIG_IP_NF_AMANDA_MODULE 1
#define CONFIG_IP_NF_QUEUE_MODULE 1
#define CONFIG_IP_NF_IPTABLES_MODULE 1
#define CONFIG_IP_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP_NF_MATCH_IPRANGE_MODULE 1
#define CONFIG_IP_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP_NF_MATCH_PKTTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP_NF_MATCH_TOS_MODULE 1
#define CONFIG_IP_NF_MATCH_RECENT_MODULE 1
#define CONFIG_IP_NF_MATCH_ECN_MODULE 1
#define CONFIG_IP_NF_MATCH_DSCP_MODULE 1
#define CONFIG_IP_NF_MATCH_AH_ESP_MODULE 1
#define CONFIG_IP_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP_NF_MATCH_TTL_MODULE 1
#define CONFIG_IP_NF_MATCH_TCPMSS_MODULE 1
#define CONFIG_IP_NF_MATCH_HELPER_MODULE 1
#define CONFIG_IP_NF_MATCH_STATE_MODULE 1
#define CONFIG_IP_NF_MATCH_CONNTRACK_MODULE 1
#define CONFIG_IP_NF_MATCH_OWNER_MODULE 1
#define CONFIG_IP_NF_MATCH_PHYSDEV_MODULE 1
#define CONFIG_IP_NF_MATCH_ADDRTYPE_MODULE 1
#define CONFIG_IP_NF_MATCH_REALM_MODULE 1
#define CONFIG_IP_NF_MATCH_SCTP_MODULE 1
#define CONFIG_IP_NF_MATCH_COMMENT_MODULE 1
#define CONFIG_IP_NF_FILTER_MODULE 1
#define CONFIG_IP_NF_TARGET_REJECT_MODULE 1
#define CONFIG_IP_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP_NF_TARGET_ULOG_MODULE 1
#define CONFIG_IP_NF_TARGET_TCPMSS_MODULE 1
#define CONFIG_IP_NF_NAT_MODULE 1
#define CONFIG_IP_NF_NAT_NEEDED 1
#define CONFIG_IP_NF_TARGET_MASQUERADE_MODULE 1
#define CONFIG_IP_NF_TARGET_REDIRECT_MODULE 1
#define CONFIG_IP_NF_TARGET_NETMAP_MODULE 1
#define CONFIG_IP_NF_TARGET_SAME_MODULE 1
#define CONFIG_IP_NF_NAT_LOCAL 1
#define CONFIG_IP_NF_NAT_SNMP_BASIC_MODULE 1
#define CONFIG_IP_NF_NAT_IRC_MODULE 1
#define CONFIG_IP_NF_NAT_FTP_MODULE 1
#define CONFIG_IP_NF_NAT_TFTP_MODULE 1
#define CONFIG_IP_NF_NAT_AMANDA_MODULE 1
#define CONFIG_IP_NF_MANGLE_MODULE 1
#define CONFIG_IP_NF_TARGET_TOS_MODULE 1
#define CONFIG_IP_NF_TARGET_ECN_MODULE 1
#define CONFIG_IP_NF_TARGET_DSCP_MODULE 1
#define CONFIG_IP_NF_TARGET_MARK_MODULE 1
#define CONFIG_IP_NF_TARGET_CLASSIFY_MODULE 1
#define CONFIG_IP_NF_RAW_MODULE 1
#define CONFIG_IP_NF_TARGET_NOTRACK_MODULE 1
#define CONFIG_IP_NF_ARPTABLES_MODULE 1
#define CONFIG_IP_NF_ARPFILTER_MODULE 1
#define CONFIG_IP_NF_ARP_MANGLE_MODULE 1
#undef CONFIG_IP_NF_COMPAT_IPCHAINS
#undef CONFIG_IP_NF_COMPAT_IPFWADM

/*
 * IPv6: Netfilter Configuration
 */
#undef CONFIG_IP6_NF_QUEUE
#define CONFIG_IP6_NF_IPTABLES_MODULE 1
#define CONFIG_IP6_NF_MATCH_LIMIT_MODULE 1
#define CONFIG_IP6_NF_MATCH_MAC_MODULE 1
#define CONFIG_IP6_NF_MATCH_RT_MODULE 1
#define CONFIG_IP6_NF_MATCH_OPTS_MODULE 1
#define CONFIG_IP6_NF_MATCH_FRAG_MODULE 1
#define CONFIG_IP6_NF_MATCH_HL_MODULE 1
#define CONFIG_IP6_NF_MATCH_MULTIPORT_MODULE 1
#define CONFIG_IP6_NF_MATCH_OWNER_MODULE 1
#define CONFIG_IP6_NF_MATCH_MARK_MODULE 1
#define CONFIG_IP6_NF_MATCH_IPV6HEADER_MODULE 1
#define CONFIG_IP6_NF_MATCH_AHESP_MODULE 1
#define CONFIG_IP6_NF_MATCH_LENGTH_MODULE 1
#define CONFIG_IP6_NF_MATCH_EUI64_MODULE 1
#define CONFIG_IP6_NF_MATCH_PHYSDEV_MODULE 1
#define CONFIG_IP6_NF_FILTER_MODULE 1
#define CONFIG_IP6_NF_TARGET_LOG_MODULE 1
#define CONFIG_IP6_NF_MANGLE_MODULE 1
#define CONFIG_IP6_NF_TARGET_MARK_MODULE 1
#define CONFIG_IP6_NF_RAW_MODULE 1

/*
 * Bridge: Netfilter Configuration
 */
#define CONFIG_BRIDGE_NF_EBTABLES_MODULE 1
#define CONFIG_BRIDGE_EBT_BROUTE_MODULE 1
#define CONFIG_BRIDGE_EBT_T_FILTER_MODULE 1
#define CONFIG_BRIDGE_EBT_T_NAT_MODULE 1
#define CONFIG_BRIDGE_EBT_802_3_MODULE 1
#define CONFIG_BRIDGE_EBT_AMONG_MODULE 1
#define CONFIG_BRIDGE_EBT_ARP_MODULE 1
#define CONFIG_BRIDGE_EBT_IP_MODULE 1
#define CONFIG_BRIDGE_EBT_LIMIT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_MODULE 1
#define CONFIG_BRIDGE_EBT_PKTTYPE_MODULE 1
#define CONFIG_BRIDGE_EBT_STP_MODULE 1
#define CONFIG_BRIDGE_EBT_VLAN_MODULE 1
#define CONFIG_BRIDGE_EBT_ARPREPLY_MODULE 1
#define CONFIG_BRIDGE_EBT_DNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_MARK_T_MODULE 1
#define CONFIG_BRIDGE_EBT_REDIRECT_MODULE 1
#define CONFIG_BRIDGE_EBT_SNAT_MODULE 1
#define CONFIG_BRIDGE_EBT_LOG_MODULE 1
#define CONFIG_XFRM 1
#define CONFIG_XFRM_USER 1

/*
 * SCTP Configuration (EXPERIMENTAL)
 */
#define CONFIG_IP_SCTP_MODULE 1
#undef CONFIG_SCTP_DBG_MSG
#undef CONFIG_SCTP_DBG_OBJCNT
#undef CONFIG_SCTP_HMAC_NONE
#undef CONFIG_SCTP_HMAC_SHA1
#define CONFIG_SCTP_HMAC_MD5 1
#define CONFIG_ATM_MODULE 1
#define CONFIG_ATM_CLIP_MODULE 1
#undef CONFIG_ATM_CLIP_NO_ICMP
#define CONFIG_ATM_LANE_MODULE 1
#undef CONFIG_ATM_MPOA
#define CONFIG_ATM_BR2684_MODULE 1
#undef CONFIG_ATM_BR2684_IPFILTER
#define CONFIG_BRIDGE_MODULE 1
#define CONFIG_VLAN_8021Q_MODULE 1
#undef CONFIG_DECNET
#define CONFIG_LLC 1
#undef CONFIG_LLC2
#undef CONFIG_IPX
#undef CONFIG_ATALK
#undef CONFIG_X25
#undef CONFIG_LAPB
#define CONFIG_NET_DIVERT 1
#undef CONFIG_ECONET
#undef CONFIG_WAN_ROUTER

/*
 * QoS and/or fair queueing
 */
#define CONFIG_NET_SCHED 1
#define CONFIG_NET_SCH_CLK_JIFFIES 1
#undef CONFIG_NET_SCH_CLK_GETTIMEOFDAY
#undef CONFIG_NET_SCH_CLK_CPU
#define CONFIG_NET_SCH_CBQ_MODULE 1
#define CONFIG_NET_SCH_HTB_MODULE 1
#define CONFIG_NET_SCH_HFSC_MODULE 1
#define CONFIG_NET_SCH_ATM_MODULE 1
#define CONFIG_NET_SCH_PRIO_MODULE 1
#define CONFIG_NET_SCH_RED_MODULE 1
#define CONFIG_NET_SCH_SFQ_MODULE 1
#define CONFIG_NET_SCH_TEQL_MODULE 1
#define CONFIG_NET_SCH_TBF_MODULE 1
#define CONFIG_NET_SCH_GRED_MODULE 1
#define CONFIG_NET_SCH_DSMARK_MODULE 1
#define CONFIG_NET_SCH_NETEM_MODULE 1
#define CONFIG_NET_SCH_INGRESS_MODULE 1
#define CONFIG_NET_QOS 1
#define CONFIG_NET_ESTIMATOR 1
#define CONFIG_NET_CLS 1
#define CONFIG_NET_CLS_TCINDEX_MODULE 1
#define CONFIG_NET_CLS_ROUTE4_MODULE 1
#define CONFIG_NET_CLS_ROUTE 1
#define CONFIG_NET_CLS_FW_MODULE 1
#define CONFIG_NET_CLS_U32_MODULE 1
#define CONFIG_CLS_U32_PERF 1
#define CONFIG_NET_CLS_IND 1
#define CONFIG_NET_CLS_RSVP_MODULE 1
#define CONFIG_NET_CLS_RSVP6_MODULE 1
#undef CONFIG_NET_CLS_ACT
#define CONFIG_NET_CLS_POLICE 1

/*
 * Network testing
 */
#undef CONFIG_NET_PKTGEN
#define CONFIG_NETPOLL 1
#undef CONFIG_NETPOLL_RX
#define CONFIG_NETPOLL_TRAP 1
#define CONFIG_NET_POLL_CONTROLLER 1
#undef CONFIG_HAMRADIO
#undef CONFIG_IRDA
#define CONFIG_BT_MODULE 1
#define CONFIG_BT_L2CAP_MODULE 1
#define CONFIG_BT_SCO_MODULE 1
#define CONFIG_BT_RFCOMM_MODULE 1
#define CONFIG_BT_RFCOMM_TTY 1
#define CONFIG_BT_BNEP_MODULE 1
#define CONFIG_BT_BNEP_MC_FILTER 1
#define CONFIG_BT_BNEP_PROTO_FILTER 1
#define CONFIG_BT_CMTP_MODULE 1
#define CONFIG_BT_HIDP_MODULE 1

/*
 * Bluetooth device drivers
 */
#define CONFIG_BT_HCIUSB_MODULE 1
#define CONFIG_BT_HCIUSB_SCO 1
#define CONFIG_BT_HCIUART_MODULE 1
#define CONFIG_BT_HCIUART_H4 1
#define CONFIG_BT_HCIUART_BCSP 1
#define CONFIG_BT_HCIUART_BCSP_TXCRC 1
#define CONFIG_BT_HCIBCM203X_MODULE 1
#define CONFIG_BT_HCIBFUSB_MODULE 1
#define CONFIG_BT_HCIDTL1_MODULE 1
#define CONFIG_BT_HCIBT3C_MODULE 1
#define CONFIG_BT_HCIBLUECARD_MODULE 1
#define CONFIG_BT_HCIBTUART_MODULE 1
#define CONFIG_BT_HCIVHCI_MODULE 1
#define CONFIG_TUX_MODULE 1

/*
 * TUX options
 */
#define CONFIG_TUX_EXTCGI 1
#undef CONFIG_TUX_EXTENDED_LOG
#undef CONFIG_TUX_DEBUG
#define CONFIG_NETDEVICES 1
#define CONFIG_DUMMY_MODULE 1
#define CONFIG_BONDING_MODULE 1
#undef CONFIG_EQUALIZER
#define CONFIG_TUN_MODULE 1
#define CONFIG_ETHERTAP_MODULE 1

/*
 * ARCnet devices
 */
#undef CONFIG_ARCNET

/*
 * Ethernet (10 or 100Mbit)
 */
#define CONFIG_NET_ETHERNET 1
#define CONFIG_MII_MODULE 1
#define CONFIG_HAPPYMEAL_MODULE 1
#define CONFIG_SUNGEM_MODULE 1
#define CONFIG_NET_VENDOR_3COM 1
#define CONFIG_VORTEX_MODULE 1
#define CONFIG_TYPHOON_MODULE 1

/*
 * Tulip family network device support
 */
#define CONFIG_NET_TULIP 1
#define CONFIG_DE2104X_MODULE 1
#define CONFIG_TULIP_MODULE 1
#undef CONFIG_TULIP_MWI
#define CONFIG_TULIP_MMIO 1
#undef CONFIG_TULIP_NAPI
#define CONFIG_DE4X5_MODULE 1
#define CONFIG_WINBOND_840_MODULE 1
#define CONFIG_DM9102_MODULE 1
#define CONFIG_PCMCIA_XIRCOM_MODULE 1
#undef CONFIG_PCMCIA_XIRTULIP
#undef CONFIG_HP100
#define CONFIG_NET_PCI 1
#define CONFIG_PCNET32_MODULE 1
#define CONFIG_AMD8111_ETH_MODULE 1
#define CONFIG_AMD8111E_NAPI 1
#define CONFIG_ADAPTEC_STARFIRE_MODULE 1
#define CONFIG_ADAPTEC_STARFIRE_NAPI 1
#define CONFIG_B44_MODULE 1
#define CONFIG_FORCEDETH_MODULE 1
#undef CONFIG_DGRS
#define CONFIG_EEPRO100_MODULE 1
#undef CONFIG_EEPRO100_PIO
#define CONFIG_E100_MODULE 1
#define CONFIG_E100_NAPI 1
#define CONFIG_FEALNX_MODULE 1
#define CONFIG_NATSEMI_MODULE 1
#define CONFIG_NE2K_PCI_MODULE 1
#define CONFIG_8139CP_MODULE 1
#define CONFIG_8139TOO_MODULE 1
#define CONFIG_8139TOO_PIO 1
#undef CONFIG_8139TOO_TUNE_TWISTER
#define CONFIG_8139TOO_8129 1
#undef CONFIG_8139_OLD_RX_RESET
#define CONFIG_SIS900_MODULE 1
#define CONFIG_EPIC100_MODULE 1
#undef CONFIG_SUNDANCE
#define CONFIG_VIA_RHINE_MODULE 1
#define CONFIG_VIA_RHINE_MMIO 1

/*
 * Ethernet (1000 Mbit)
 */
#define CONFIG_ACENIC_MODULE 1
#undef CONFIG_ACENIC_OMIT_TIGON_I
#define CONFIG_DL2K_MODULE 1
#define CONFIG_E1000_MODULE 1
#define CONFIG_E1000_NAPI 1
#define CONFIG_NS83820_MODULE 1
#undef CONFIG_HAMACHI
#undef CONFIG_YELLOWFIN
#define CONFIG_R8169_MODULE 1
#define CONFIG_R8169_NAPI 1
#define CONFIG_SK98LIN_MODULE 1
#define CONFIG_VIA_VELOCITY_MODULE 1
#define CONFIG_TIGON3_MODULE 1

/*
 * Ethernet (10000 Mbit)
 */
#define CONFIG_IXGB_MODULE 1
#define CONFIG_IXGB_NAPI 1
#define CONFIG_S2IO_MODULE 1
#define CONFIG_S2IO_NAPI 1

/*
 * Token Ring devices
 */
#define CONFIG_TR 1
#define CONFIG_IBMOL_MODULE 1
#define CONFIG_3C359_MODULE 1
#define CONFIG_TMS380TR_MODULE 1
#define CONFIG_TMSPCI_MODULE 1
#define CONFIG_ABYSS_MODULE 1

/*
 * Wireless LAN (non-hamradio)
 */
#define CONFIG_NET_RADIO 1

/*
 * Obsolete Wireless cards support (pre-802.11)
 */
#undef CONFIG_STRIP
#define CONFIG_PCMCIA_WAVELAN_MODULE 1
#define CONFIG_PCMCIA_NETWAVE_MODULE 1

/*
 * Wireless 802.11 Frequency Hopping cards support
 */
#undef CONFIG_PCMCIA_RAYCS

/*
 * Wireless 802.11b ISA/PCI cards support
 */
#define CONFIG_IEEE80211_MODULE 1
#undef CONFIG_IEEE80211_DEBUG
#define CONFIG_IEEE80211_CRYPT_MODULE 1
#define CONFIG_IEEE80211_WPA_MODULE 1
#define CONFIG_IEEE80211_CRYPT_TKIP_MODULE 1
#define CONFIG_IPW2100_MODULE 1
#undef CONFIG_IPW_DEBUG
#define CONFIG_IPW2100_PROMISC 1
#undef CONFIG_IPW2100_LEGACY_FW_LOAD
#define CONFIG_IPW2200_MODULE 1
#define CONFIG_HERMES_MODULE 1
#define CONFIG_PLX_HERMES_MODULE 1
#define CONFIG_TMD_HERMES_MODULE 1
#define CONFIG_PCI_HERMES_MODULE 1
#define CONFIG_ATMEL_MODULE 1
#define CONFIG_PCI_ATMEL_MODULE 1

/*
 * Wireless 802.11b Pcmcia/Cardbus cards support
 */
#define CONFIG_PCMCIA_HERMES_MODULE 1
#define CONFIG_AIRO_CS_MODULE 1
#define CONFIG_PCMCIA_ATMEL_MODULE 1
#define CONFIG_PCMCIA_WL3501_MODULE 1

/*
 * Prism GT/Duette 802.11(a/b/g) PCI/Cardbus support
 */
#define CONFIG_PRISM54_MODULE 1
#define CONFIG_NET_WIRELESS 1

/*
 * PCMCIA network device support
 */
#define CONFIG_NET_PCMCIA 1
#define CONFIG_PCMCIA_3C589_MODULE 1
#define CONFIG_PCMCIA_3C574_MODULE 1
#define CONFIG_PCMCIA_FMVJ18X_MODULE 1
#define CONFIG_PCMCIA_PCNET_MODULE 1
#define CONFIG_PCMCIA_NMCLAN_MODULE 1
#define CONFIG_PCMCIA_SMC91C92_MODULE 1
#define CONFIG_PCMCIA_XIRC2PS_MODULE 1
#define CONFIG_PCMCIA_AXNET_MODULE 1

/*
 * Wan interfaces
 */
#undef CONFIG_WAN

/*
 * ATM drivers
 */
#define CONFIG_ATM_TCP_MODULE 1
#define CONFIG_ATM_LANAI_MODULE 1
#define CONFIG_ATM_ENI_MODULE 1
#undef CONFIG_ATM_ENI_DEBUG
#undef CONFIG_ATM_ENI_TUNE_BURST
#define CONFIG_ATM_FIRESTREAM_MODULE 1
#undef CONFIG_ATM_ZATM
#define CONFIG_ATM_IDT77252_MODULE 1
#undef CONFIG_ATM_IDT77252_DEBUG
#undef CONFIG_ATM_IDT77252_RCV_ALL
#define CONFIG_ATM_IDT77252_USE_SUNI 1
#define CONFIG_ATM_AMBASSADOR_MODULE 1
#undef CONFIG_ATM_AMBASSADOR_DEBUG
#define CONFIG_ATM_HORIZON_MODULE 1
#undef CONFIG_ATM_HORIZON_DEBUG
#define CONFIG_ATM_FORE200E_MAYBE_MODULE 1
#undef CONFIG_ATM_FORE200E_PCA
#define CONFIG_ATM_HE_MODULE 1
#undef CONFIG_ATM_HE_USE_SUNI
#define CONFIG_FDDI 1
#undef CONFIG_DEFXX
#undef CONFIG_SKFP
#undef CONFIG_HIPPI
#undef CONFIG_PLIP
#define CONFIG_PPP_MODULE 1
#define CONFIG_PPP_MULTILINK 1
#define CONFIG_PPP_FILTER 1
#define CONFIG_PPP_ASYNC_MODULE 1
#define CONFIG_PPP_SYNC_TTY_MODULE 1
#define CONFIG_PPP_DEFLATE_MODULE 1
#undef CONFIG_PPP_BSDCOMP
#define CONFIG_PPPOE_MODULE 1
#define CONFIG_PPPOATM_MODULE 1
#undef CONFIG_SLIP
#define CONFIG_NET_FC 1
#undef CONFIG_SHAPER
#define CONFIG_NETCONSOLE_MODULE 1
#define CONFIG_NETDUMP_MODULE 1

/*
 * ISDN subsystem
 */
#define CONFIG_ISDN_MODULE 1

/*
 * Old ISDN4Linux
 */
#define CONFIG_ISDN_I4L_MODULE 1
#define CONFIG_ISDN_PPP 1
#define CONFIG_ISDN_PPP_VJ 1
#define CONFIG_ISDN_MPP 1
#define CONFIG_IPPP_FILTER 1
#undef CONFIG_ISDN_PPP_BSDCOMP
#define CONFIG_ISDN_AUDIO 1
#define CONFIG_ISDN_TTY_FAX 1

/*
 * ISDN feature submodules
 */
#define CONFIG_ISDN_DRV_LOOP_MODULE 1

/*
 * ISDN4Linux hardware drivers
 */

/*
 * Passive cards
 */
#define CONFIG_ISDN_DRV_HISAX_MODULE 1

/*
 * D-channel protocol features
 */
#define CONFIG_HISAX_EURO 1
#define CONFIG_DE_AOC 1
#define CONFIG_HISAX_NO_SENDCOMPLETE 1
#define CONFIG_HISAX_NO_LLC 1
#define CONFIG_HISAX_NO_KEYPAD 1
#define CONFIG_HISAX_1TR6 1
#define CONFIG_HISAX_NI1 1
#define CONFIG_HISAX_MAX_CARDS 8

/*
 * HiSax supported cards
 */
#define CONFIG_HISAX_16_3 1
#define CONFIG_HISAX_TELESPCI 1
#define CONFIG_HISAX_S0BOX 1
#define CONFIG_HISAX_FRITZPCI 1
#define CONFIG_HISAX_AVM_A1_PCMCIA 1
#define CONFIG_HISAX_ELSA 1
#define CONFIG_HISAX_DIEHLDIVA 1
#define CONFIG_HISAX_SEDLBAUER 1
#define CONFIG_HISAX_NETJET 1
#define CONFIG_HISAX_NETJET_U 1
#define CONFIG_HISAX_NICCY 1
#define CONFIG_HISAX_BKM_A4T 1
#define CONFIG_HISAX_SCT_QUADRO 1
#define CONFIG_HISAX_GAZEL 1
#define CONFIG_HISAX_HFC_PCI 1
#define CONFIG_HISAX_W6692 1
#define CONFIG_HISAX_HFC_SX 1
#define CONFIG_HISAX_ENTERNOW_PCI 1
#undef CONFIG_HISAX_DEBUG

/*
 * HiSax PCMCIA card service modules
 */
#define CONFIG_HISAX_SEDLBAUER_CS_MODULE 1
#define CONFIG_HISAX_ELSA_CS_MODULE 1
#define CONFIG_HISAX_AVM_A1_CS_MODULE 1
#define CONFIG_HISAX_TELES_CS_MODULE 1

/*
 * HiSax sub driver modules
 */
#define CONFIG_HISAX_ST5481_MODULE 1
#define CONFIG_HISAX_HFCUSB_MODULE 1
#define CONFIG_HISAX_FRITZ_PCIPNP_MODULE 1
#define CONFIG_HISAX_HDLC 1

/*
 * Active cards
 */
#define CONFIG_ISDN_DRV_TPAM_MODULE 1
#define CONFIG_HYSDN_MODULE 1
#define CONFIG_HYSDN_CAPI 1

/*
 * CAPI subsystem
 */
#define CONFIG_ISDN_CAPI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_VERBOSE_REASON 1
#define CONFIG_ISDN_CAPI_MIDDLEWARE 1
#define CONFIG_ISDN_CAPI_CAPI20_MODULE 1
#define CONFIG_ISDN_CAPI_CAPIFS_BOOL 1
#define CONFIG_ISDN_CAPI_CAPIFS_MODULE 1
#define CONFIG_ISDN_CAPI_CAPIDRV_MODULE 1

/*
 * CAPI hardware drivers
 */

/*
 * Active AVM cards
 */
#define CONFIG_CAPI_AVM 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCIV4 1
#define CONFIG_ISDN_DRV_AVMB1_B1PCMCIA_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_AVM_CS_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_T1PCI_MODULE 1
#define CONFIG_ISDN_DRV_AVMB1_C4_MODULE 1

/*
 * Active Eicon DIVA Server cards
 */
#undef CONFIG_CAPI_EICON

/*
 * Telephony Support
 */
#undef CONFIG_PHONE

/*
 * Input device support
 */
#define CONFIG_INPUT 1

/*
 * Userland interfaces
 */
#define CONFIG_INPUT_MOUSEDEV 1
#undef CONFIG_INPUT_MOUSEDEV_PSAUX
#define CONFIG_INPUT_MOUSEDEV_SCREEN_X 1024
#define CONFIG_INPUT_MOUSEDEV_SCREEN_Y 768
#define CONFIG_INPUT_JOYDEV_MODULE 1
#undef CONFIG_INPUT_TSDEV
#define CONFIG_INPUT_EVDEV 1
#undef CONFIG_INPUT_EVBUG

/*
 * Input I/O drivers
 */
#undef CONFIG_GAMEPORT
#define CONFIG_SOUND_GAMEPORT 1
#define CONFIG_SERIO 1
#define CONFIG_SERIO_I8042 1
#define CONFIG_SERIO_SERPORT 1
#undef CONFIG_SERIO_CT82C710
#undef CONFIG_SERIO_PARKBD
#undef CONFIG_SERIO_PCIPS2
#undef CONFIG_SERIO_RAW

/*
 * Input Device Drivers
 */
#define CONFIG_INPUT_KEYBOARD 1
#define CONFIG_KEYBOARD_ATKBD 1
#undef CONFIG_KEYBOARD_SUNKBD
#undef CONFIG_KEYBOARD_LKKBD
#undef CONFIG_KEYBOARD_XTKBD
#undef CONFIG_KEYBOARD_NEWTON
#define CONFIG_INPUT_MOUSE 1
#define CONFIG_MOUSE_PS2 1
#define CONFIG_MOUSE_SERIAL_MODULE 1
#define CONFIG_MOUSE_VSXXXAA_MODULE 1
#define CONFIG_INPUT_JOYSTICK 1
#undef CONFIG_JOYSTICK_IFORCE
#undef CONFIG_JOYSTICK_WARRIOR
#undef CONFIG_JOYSTICK_MAGELLAN
#undef CONFIG_JOYSTICK_SPACEORB
#undef CONFIG_JOYSTICK_SPACEBALL
#undef CONFIG_JOYSTICK_STINGER
#undef CONFIG_JOYSTICK_TWIDDLER
#undef CONFIG_JOYSTICK_DB9
#undef CONFIG_JOYSTICK_GAMECON
#undef CONFIG_JOYSTICK_TURBOGRAFX
#define CONFIG_INPUT_TOUCHSCREEN 1
#define CONFIG_TOUCHSCREEN_GUNZE_MODULE 1
#define CONFIG_INPUT_MISC 1
#define CONFIG_INPUT_PCSPKR_MODULE 1
#define CONFIG_INPUT_UINPUT_MODULE 1

/*
 * Character devices
 */
#define CONFIG_VT 1
#define CONFIG_VT_CONSOLE 1
#define CONFIG_HW_CONSOLE 1
#define CONFIG_SERIAL_NONSTANDARD 1
#undef CONFIG_COMPUTONE
#undef CONFIG_ROCKETPORT
#undef CONFIG_CYCLADES
#undef CONFIG_DIGIEPCA
#undef CONFIG_DIGI
#undef CONFIG_MOXA_INTELLIO
#undef CONFIG_MOXA_SMARTIO
#undef CONFIG_ISI
#undef CONFIG_SYNCLINK
#undef CONFIG_SYNCLINKMP
#define CONFIG_N_HDLC_MODULE 1
#undef CONFIG_RISCOM8
#undef CONFIG_SPECIALIX
#undef CONFIG_SX
#undef CONFIG_RIO
#define CONFIG_STALDRV 1
#undef CONFIG_STALLION
#undef CONFIG_ISTALLION

/*
 * Serial drivers
 */
#define CONFIG_SERIAL_8250 1
#define CONFIG_SERIAL_8250_CONSOLE 1
#define CONFIG_SERIAL_8250_CS_MODULE 1
#undef CONFIG_SERIAL_8250_ACPI
#define CONFIG_SERIAL_8250_NR_UARTS 4
#define CONFIG_SERIAL_8250_EXTENDED 1
#undef CONFIG_SERIAL_8250_MANY_PORTS
#define CONFIG_SERIAL_8250_SHARE_IRQ 1
#define CONFIG_SERIAL_8250_DETECT_IRQ 1
#define CONFIG_SERIAL_8250_MULTIPORT 1
#define CONFIG_SERIAL_8250_RSA 1

/*
 * Non-8250 serial port support
 */
#define CONFIG_SERIAL_CORE 1
#define CONFIG_SERIAL_CORE_CONSOLE 1
#define CONFIG_UNIX98_PTYS 1
#undef CONFIG_LEGACY_PTYS
#define CONFIG_CRASH_MODULE 1
#define CONFIG_PRINTER_MODULE 1
#define CONFIG_LP_CONSOLE 1
#define CONFIG_PPDEV_MODULE 1
#undef CONFIG_TIPAR

/*
 * IPMI
 */
#define CONFIG_IPMI_HANDLER_MODULE 1
#undef CONFIG_IPMI_PANIC_EVENT
#define CONFIG_IPMI_DEVICE_INTERFACE_MODULE 1
#define CONFIG_IPMI_SI_MODULE 1
#define CONFIG_IPMI_WATCHDOG_MODULE 1
#define CONFIG_IPMI_POWEROFF_MODULE 1

/*
 * Watchdog Cards
 */
#define CONFIG_WATCHDOG 1
#undef CONFIG_WATCHDOG_NOWAYOUT

/*
 * Watchdog Device Drivers
 */
#define CONFIG_SOFT_WATCHDOG_MODULE 1
#define CONFIG_ACQUIRE_WDT_MODULE 1
#define CONFIG_ADVANTECH_WDT_MODULE 1
#define CONFIG_ALIM1535_WDT_MODULE 1
#define CONFIG_ALIM7101_WDT_MODULE 1
#define CONFIG_SC520_WDT_MODULE 1
#define CONFIG_EUROTECH_WDT_MODULE 1
#define CONFIG_IB700_WDT_MODULE 1
#define CONFIG_WAFER_WDT_MODULE 1
#define CONFIG_I8XX_TCO_MODULE 1
#define CONFIG_SC1200_WDT_MODULE 1
#undef CONFIG_SCx200_WDT
#undef CONFIG_60XX_WDT
#define CONFIG_CPU5_WDT_MODULE 1
#define CONFIG_W83627HF_WDT_MODULE 1
#define CONFIG_W83877F_WDT_MODULE 1
#define CONFIG_MACHZ_WDT_MODULE 1

/*
 * PCI-based Watchdog Cards
 */
#define CONFIG_PCIPCWATCHDOG_MODULE 1
#define CONFIG_WDTPCI_MODULE 1
#define CONFIG_WDT_501_PCI 1

/*
 * USB-based Watchdog Cards
 */
#define CONFIG_USBPCWATCHDOG_MODULE 1
#define CONFIG_HW_RANDOM_MODULE 1
#undef CONFIG_NVRAM
#define CONFIG_RTC 1
#define CONFIG_DTLK_MODULE 1
#undef CONFIG_R3964
#undef CONFIG_APPLICOM

/*
 * Ftape, the floppy tape device driver
 */
#undef CONFIG_FTAPE
#define CONFIG_AGP 1
#define CONFIG_AGP_AMD64 1
#define CONFIG_AGP_INTEL_MCH 1
#define CONFIG_DRM 1
#undef CONFIG_DRM_TDFX
#define CONFIG_DRM_R128_MODULE 1
#define CONFIG_DRM_RADEON_MODULE 1
#define CONFIG_DRM_MGA_MODULE 1
#undef CONFIG_DRM_SIS

/*
 * PCMCIA character devices
 */
#undef CONFIG_SYNCLINK_CS
#undef CONFIG_MWAVE
#define CONFIG_RAW_DRIVER 1
#undef CONFIG_HPET
#define CONFIG_MAX_RAW_DEVS 8192
#define CONFIG_HANGCHECK_TIMER_MODULE 1

/*
 * I2C support
 */
#define CONFIG_I2C_MODULE 1
#define CONFIG_I2C_CHARDEV_MODULE 1

/*
 * I2C Algorithms
 */
#define CONFIG_I2C_ALGOBIT_MODULE 1
#define CONFIG_I2C_ALGOPCF_MODULE 1
#define CONFIG_I2C_ALGOPCA_MODULE 1

/*
 * I2C Hardware Bus support
 */
#define CONFIG_I2C_ALI1535_MODULE 1
#define CONFIG_I2C_ALI1563_MODULE 1
#define CONFIG_I2C_ALI15X3_MODULE 1
#define CONFIG_I2C_AMD756_MODULE 1
#define CONFIG_I2C_AMD8111_MODULE 1
#define CONFIG_I2C_I801_MODULE 1
#define CONFIG_I2C_I810_MODULE 1
#define CONFIG_I2C_ISA_MODULE 1
#define CONFIG_I2C_NFORCE2_MODULE 1
#undef CONFIG_I2C_PARPORT
#undef CONFIG_I2C_PARPORT_LIGHT
#define CONFIG_I2C_PROSAVAGE_MODULE 1
#define CONFIG_I2C_SAVAGE4_MODULE 1
#undef CONFIG_SCx200_ACB
#define CONFIG_I2C_SIS5595_MODULE 1
#define CONFIG_I2C_SIS630_MODULE 1
#define CONFIG_I2C_SIS96X_MODULE 1
#define CONFIG_I2C_VIA_MODULE 1
#define CONFIG_I2C_VIAPRO_MODULE 1
#define CONFIG_I2C_VOODOO3_MODULE 1
#undef CONFIG_I2C_PCA_ISA

/*
 * Hardware Sensors Chip support
 */
#define CONFIG_I2C_SENSOR_MODULE 1
#define CONFIG_SENSORS_ADM1021_MODULE 1
#define CONFIG_SENSORS_ADM1025_MODULE 1
#define CONFIG_SENSORS_ADM1031_MODULE 1
#define CONFIG_SENSORS_ASB100_MODULE 1
#define CONFIG_SENSORS_DS1621_MODULE 1
#define CONFIG_SENSORS_FSCHER_MODULE 1
#define CONFIG_SENSORS_GL518SM_MODULE 1
#define CONFIG_SENSORS_IT87_MODULE 1
#define CONFIG_SENSORS_LM75_MODULE 1
#define CONFIG_SENSORS_LM77_MODULE 1
#define CONFIG_SENSORS_LM78_MODULE 1
#define CONFIG_SENSORS_LM80_MODULE 1
#define CONFIG_SENSORS_LM83_MODULE 1
#define CONFIG_SENSORS_LM85_MODULE 1
#define CONFIG_SENSORS_LM90_MODULE 1
#define CONFIG_SENSORS_MAX1619_MODULE 1
#define CONFIG_SENSORS_SMSC47M1_MODULE 1
#define CONFIG_SENSORS_VIA686A_MODULE 1
#define CONFIG_SENSORS_W83781D_MODULE 1
#define CONFIG_SENSORS_W83L785TS_MODULE 1
#define CONFIG_SENSORS_W83627HF_MODULE 1

/*
 * Other I2C Chip support
 */
#define CONFIG_SENSORS_EEPROM_MODULE 1
#define CONFIG_SENSORS_PCF8574_MODULE 1
#define CONFIG_SENSORS_PCF8591_MODULE 1
#define CONFIG_SENSORS_RTC8564_MODULE 1
#undef CONFIG_I2C_DEBUG_CORE
#undef CONFIG_I2C_DEBUG_ALGO
#undef CONFIG_I2C_DEBUG_BUS
#undef CONFIG_I2C_DEBUG_CHIP

/*
 * Dallas's 1-wire bus
 */
#undef CONFIG_W1

/*
 * Misc devices
 */
#undef CONFIG_IBM_ASM

/*
 * Multimedia devices
 */
#define CONFIG_VIDEO_DEV_MODULE 1

/*
 * Video For Linux
 */

/*
 * Video Adapters
 */
#undef CONFIG_VIDEO_BT848
#undef CONFIG_VIDEO_BWQCAM
#undef CONFIG_VIDEO_CQCAM
#undef CONFIG_VIDEO_W9966
#undef CONFIG_VIDEO_CPIA
#undef CONFIG_VIDEO_SAA5246A
#undef CONFIG_VIDEO_SAA5249
#undef CONFIG_TUNER_3036
#undef CONFIG_VIDEO_STRADIS
#undef CONFIG_VIDEO_ZORAN
#undef CONFIG_VIDEO_SAA7134
#undef CONFIG_VIDEO_MXB
#undef CONFIG_VIDEO_DPC
#undef CONFIG_VIDEO_HEXIUM_ORION
#undef CONFIG_VIDEO_HEXIUM_GEMINI
#undef CONFIG_VIDEO_CX88
#define CONFIG_VIDEO_OVCAMCHIP_MODULE 1

/*
 * Radio Adapters
 */
#undef CONFIG_RADIO_GEMTEK_PCI
#undef CONFIG_RADIO_MAXIRADIO
#undef CONFIG_RADIO_MAESTRO

/*
 * Digital Video Broadcasting Devices
 */
#undef CONFIG_DVB

/*
 * Graphics support
 */
#define CONFIG_FB 1
#define CONFIG_FB_MODE_HELPERS 1
#define CONFIG_FB_CIRRUS_MODULE 1
#undef CONFIG_FB_PM2
#undef CONFIG_FB_CYBER2000
#undef CONFIG_FB_ASILIANT
#undef CONFIG_FB_IMSTT
#define CONFIG_FB_VGA16_MODULE 1
#define CONFIG_FB_VESA 1
#define CONFIG_VIDEO_SELECT 1
#undef CONFIG_FB_HGA
#define CONFIG_FB_RIVA_MODULE 1
#undef CONFIG_FB_RIVA_I2C
#undef CONFIG_FB_RIVA_DEBUG
#undef CONFIG_FB_MATROX
#undef CONFIG_FB_RADEON_OLD
#undef CONFIG_FB_RADEON
#undef CONFIG_FB_ATY128
#undef CONFIG_FB_ATY
#undef CONFIG_FB_SIS
#undef CONFIG_FB_NEOMAGIC
#define CONFIG_FB_KYRO_MODULE 1
#undef CONFIG_FB_3DFX
#undef CONFIG_FB_VOODOO1
#undef CONFIG_FB_TRIDENT
#undef CONFIG_FB_VIRTUAL

/*
 * Console display driver support
 */
#define CONFIG_VGA_CONSOLE 1
#define CONFIG_DUMMY_CONSOLE 1
#define CONFIG_FRAMEBUFFER_CONSOLE 1
#undef CONFIG_FONTS
#define CONFIG_FONT_8x8 1
#define CONFIG_FONT_8x16 1

/*
 * Logo configuration
 */
#define CONFIG_LOGO 1
#undef CONFIG_LOGO_LINUX_MONO
#undef CONFIG_LOGO_LINUX_VGA16
#define CONFIG_LOGO_LINUX_CLUT224 1

/*
 * Sound
 */
#define CONFIG_SOUND_MODULE 1

/*
 * Advanced Linux Sound Architecture
 */
#define CONFIG_SND_MODULE 1
#define CONFIG_SND_TIMER_MODULE 1
#define CONFIG_SND_PCM_MODULE 1
#define CONFIG_SND_HWDEP_MODULE 1
#define CONFIG_SND_RAWMIDI_MODULE 1
#define CONFIG_SND_SEQUENCER_MODULE 1
#define CONFIG_SND_SEQ_DUMMY_MODULE 1
#define CONFIG_SND_OSSEMUL 1
#define CONFIG_SND_MIXER_OSS_MODULE 1
#define CONFIG_SND_PCM_OSS_MODULE 1
#define CONFIG_SND_SEQUENCER_OSS 1
#define CONFIG_SND_BIT32_EMUL_MODULE 1
#define CONFIG_SND_RTCTIMER_MODULE 1
#undef CONFIG_SND_VERBOSE_PRINTK
#undef CONFIG_SND_DEBUG

/*
 * Generic devices
 */
#define CONFIG_SND_MPU401_UART_MODULE 1
#define CONFIG_SND_OPL3_LIB_MODULE 1
#define CONFIG_SND_VX_LIB_MODULE 1
#define CONFIG_SND_DUMMY_MODULE 1
#define CONFIG_SND_VIRMIDI_MODULE 1
#define CONFIG_SND_MTPAV_MODULE 1
#undef CONFIG_SND_SERIAL_U16550
#define CONFIG_SND_MPU401_MODULE 1

/*
 * PCI devices
 */
#define CONFIG_SND_AC97_CODEC_MODULE 1
#define CONFIG_SND_ALI5451_MODULE 1
#define CONFIG_SND_ATIIXP_MODULE 1
#define CONFIG_SND_ATIIXP_MODEM_MODULE 1
#define CONFIG_SND_AU8810_MODULE 1
#define CONFIG_SND_AU8820_MODULE 1
#define CONFIG_SND_AU8830_MODULE 1
#define CONFIG_SND_AZT3328_MODULE 1
#define CONFIG_SND_BT87X_MODULE 1
#define CONFIG_SND_CS46XX_MODULE 1
#define CONFIG_SND_CS46XX_NEW_DSP 1
#define CONFIG_SND_CS4281_MODULE 1
#define CONFIG_SND_EMU10K1_MODULE 1
#define CONFIG_SND_KORG1212_MODULE 1
#define CONFIG_SND_MIXART_MODULE 1
#define CONFIG_SND_NM256_MODULE 1
#define CONFIG_SND_RME32_MODULE 1
#define CONFIG_SND_RME96_MODULE 1
#define CONFIG_SND_RME9652_MODULE 1
#define CONFIG_SND_HDSP_MODULE 1
#define CONFIG_SND_TRIDENT_MODULE 1
#define CONFIG_SND_YMFPCI_MODULE 1
#define CONFIG_SND_ALS4000_MODULE 1
#define CONFIG_SND_CMIPCI_MODULE 1
#define CONFIG_SND_ENS1370_MODULE 1
#define CONFIG_SND_ENS1371_MODULE 1
#define CONFIG_SND_ES1938_MODULE 1
#define CONFIG_SND_ES1968_MODULE 1
#define CONFIG_SND_MAESTRO3_MODULE 1
#define CONFIG_SND_FM801_MODULE 1
#define CONFIG_SND_FM801_TEA575X_MODULE 1
#define CONFIG_SND_ICE1712_MODULE 1
#define CONFIG_SND_ICE1724_MODULE 1
#define CONFIG_SND_INTEL8X0_MODULE 1
#define CONFIG_SND_INTEL8X0M_MODULE 1
#define CONFIG_SND_SONICVIBES_MODULE 1
#define CONFIG_SND_VIA82XX_MODULE 1
#define CONFIG_SND_VX222_MODULE 1

/*
 * ALSA USB devices
 */
#define CONFIG_SND_USB_AUDIO_MODULE 1
#define CONFIG_SND_USB_USX2Y_MODULE 1

/*
 * PCMCIA devices
 */

/*
 * Open Sound System
 */
#undef CONFIG_SOUND_PRIME

/*
 * USB support
 */
#define CONFIG_USB 1
#undef CONFIG_USB_DEBUG

/*
 * Miscellaneous USB options
 */
#define CONFIG_USB_DEVICEFS 1
#undef CONFIG_USB_BANDWIDTH
#undef CONFIG_USB_DYNAMIC_MINORS
#define CONFIG_USB_SUSPEND 1
#undef CONFIG_USB_OTG

/*
 * USB Host Controller Drivers
 */
#define CONFIG_USB_EHCI_HCD_MODULE 1
#define CONFIG_USB_EHCI_SPLIT_ISO 1
#define CONFIG_USB_EHCI_ROOT_HUB_TT 1
#define CONFIG_USB_OHCI_HCD_MODULE 1
#define CONFIG_USB_UHCI_HCD_MODULE 1

/*
 * USB Device Class drivers
 */
#undef CONFIG_USB_AUDIO

/*
 * USB Bluetooth TTY can only be used with disabled Bluetooth subsystem
 */
#define CONFIG_USB_MIDI_MODULE 1
#define CONFIG_USB_ACM_MODULE 1
#define CONFIG_USB_PRINTER_MODULE 1
#define CONFIG_USB_STORAGE_MODULE 1
#undef CONFIG_USB_STORAGE_DEBUG
#define CONFIG_USB_STORAGE_RW_DETECT 1
#define CONFIG_USB_STORAGE_DATAFAB 1
#define CONFIG_USB_STORAGE_FREECOM 1
#define CONFIG_USB_STORAGE_ISD200 1
#define CONFIG_USB_STORAGE_DPCM 1
#define CONFIG_USB_STORAGE_HP8200e 1
#define CONFIG_USB_STORAGE_SDDR09 1
#define CONFIG_USB_STORAGE_SDDR55 1
#define CONFIG_USB_STORAGE_JUMPSHOT 1

/*
 * USB Human Interface Devices (HID)
 */
#define CONFIG_USB_HID 1
#define CONFIG_USB_HIDINPUT 1
#define CONFIG_HID_FF 1
#define CONFIG_HID_PID 1
#define CONFIG_LOGITECH_FF 1
#define CONFIG_THRUSTMASTER_FF 1
#define CONFIG_USB_HIDDEV 1
#define CONFIG_USB_AIPTEK_MODULE 1
#define CONFIG_USB_WACOM_MODULE 1
#define CONFIG_USB_KBTAB_MODULE 1
#define CONFIG_USB_POWERMATE_MODULE 1
#define CONFIG_USB_MTOUCH_MODULE 1
#define CONFIG_USB_EGALAX_MODULE 1
#define CONFIG_USB_XPAD_MODULE 1
#define CONFIG_USB_ATI_REMOTE_MODULE 1

/*
 * USB Imaging devices
 */
#define CONFIG_USB_MDC800_MODULE 1
#define CONFIG_USB_MICROTEK_MODULE 1
#define CONFIG_USB_HPUSBSCSI_MODULE 1

/*
 * USB Multimedia devices
 */
#define CONFIG_USB_DABUSB_MODULE 1
#define CONFIG_USB_VICAM_MODULE 1
#define CONFIG_USB_DSBR_MODULE 1
#define CONFIG_USB_IBMCAM_MODULE 1
#define CONFIG_USB_KONICAWC_MODULE 1
#define CONFIG_USB_OV511_MODULE 1
#define CONFIG_USB_SE401_MODULE 1
#define CONFIG_USB_SN9C102_MODULE 1
#define CONFIG_USB_STV680_MODULE 1
#define CONFIG_USB_W9968CF_MODULE 1
#define CONFIG_USB_PWC_MODULE 1

/*
 * USB Network adaptors
 */
#define CONFIG_USB_CATC_MODULE 1
#define CONFIG_USB_KAWETH_MODULE 1
#define CONFIG_USB_PEGASUS_MODULE 1
#define CONFIG_USB_RTL8150_MODULE 1
#define CONFIG_USB_USBNET_MODULE 1

/*
 * USB Host-to-Host Cables
 */
#define CONFIG_USB_ALI_M5632 1
#define CONFIG_USB_AN2720 1
#define CONFIG_USB_BELKIN 1
#define CONFIG_USB_GENESYS 1
#define CONFIG_USB_NET1080 1
#define CONFIG_USB_PL2301 1

/*
 * Intelligent USB Devices/Gadgets
 */
#define CONFIG_USB_ARMLINUX 1
#define CONFIG_USB_EPSON2888 1
#define CONFIG_USB_ZAURUS 1
#define CONFIG_USB_CDCETHER 1

/*
 * USB Network Adapters
 */
#define CONFIG_USB_AX8817X 1

/*
 * USB port drivers
 */
#define CONFIG_USB_USS720_MODULE 1

/*
 * USB Serial Converter support
 */
#define CONFIG_USB_SERIAL_MODULE 1
#define CONFIG_USB_SERIAL_GENERIC 1
#define CONFIG_USB_SERIAL_BELKIN_MODULE 1
#define CONFIG_USB_SERIAL_WHITEHEAT_MODULE 1
#define CONFIG_USB_SERIAL_DIGI_ACCELEPORT_MODULE 1
#define CONFIG_USB_SERIAL_EMPEG_MODULE 1
#define CONFIG_USB_SERIAL_FTDI_SIO_MODULE 1
#define CONFIG_USB_SERIAL_VISOR_MODULE 1
#define CONFIG_USB_SERIAL_IPAQ_MODULE 1
#define CONFIG_USB_SERIAL_IR_MODULE 1
#define CONFIG_USB_SERIAL_EDGEPORT_MODULE 1
#define CONFIG_USB_SERIAL_EDGEPORT_TI_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_PDA_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_MODULE 1
#define CONFIG_USB_SERIAL_KEYSPAN_MPR 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28X 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28XA 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA28XB 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA18X 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19W 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QW 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA19QI 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA49W 1
#define CONFIG_USB_SERIAL_KEYSPAN_USA49WLC 1
#define CONFIG_USB_SERIAL_KLSI_MODULE 1
#define CONFIG_USB_SERIAL_KOBIL_SCT_MODULE 1
#define CONFIG_USB_SERIAL_MCT_U232_MODULE 1
#define CONFIG_USB_SERIAL_PL2303_MODULE 1
#define CONFIG_USB_SERIAL_SAFE_MODULE 1
#define CONFIG_USB_SERIAL_SAFE_PADDED 1
#define CONFIG_USB_SERIAL_CYBERJACK_MODULE 1
#define CONFIG_USB_SERIAL_XIRCOM_MODULE 1
#define CONFIG_USB_SERIAL_OMNINET_MODULE 1
#define CONFIG_USB_EZUSB 1

/*
 * USB Miscellaneous drivers
 */
#define CONFIG_USB_EMI62_MODULE 1
#undef CONFIG_USB_EMI26
#undef CONFIG_USB_TIGL
#define CONFIG_USB_AUERSWALD_MODULE 1
#define CONFIG_USB_RIO500_MODULE 1
#define CONFIG_USB_LEGOTOWER_MODULE 1
#define CONFIG_USB_LCD_MODULE 1
#define CONFIG_USB_LED_MODULE 1
#undef CONFIG_USB_CYTHERM
#define CONFIG_USB_PHIDGETSERVO_MODULE 1
#define CONFIG_USB_TEST_MODULE 1

/*
 * USB ATM/DSL drivers
 */
#define CONFIG_USB_ATM_MODULE 1
#define CONFIG_USB_SPEEDTOUCH_MODULE 1

/*
 * USB Gadget Support
 */
#undef CONFIG_USB_GADGET

/*
 * Firmware Drivers
 */
#define CONFIG_EDD_MODULE 1

/*
 * File systems
 */
#define CONFIG_EXT2_FS 1
#define CONFIG_EXT2_FS_XATTR 1
#define CONFIG_EXT2_FS_POSIX_ACL 1
#define CONFIG_EXT2_FS_SECURITY 1
#define CONFIG_EXT3_FS_MODULE 1
#define CONFIG_EXT3_FS_XATTR 1
#define CONFIG_EXT3_FS_POSIX_ACL 1
#define CONFIG_EXT3_FS_SECURITY 1
#define CONFIG_JBD_MODULE 1
#undef CONFIG_JBD_DEBUG
#define CONFIG_FS_MBCACHE 1
#undef CONFIG_REISERFS_FS
#undef CONFIG_JFS_FS
#define CONFIG_FS_POSIX_ACL 1
#undef CONFIG_XFS_FS
#undef CONFIG_MINIX_FS
#undef CONFIG_ROMFS_FS
#define CONFIG_QUOTA 1
#undef CONFIG_QFMT_V1
#define CONFIG_QFMT_V2 1
#define CONFIG_QUOTACTL 1
#undef CONFIG_AUTOFS_FS
#define CONFIG_AUTOFS4_FS_MODULE 1

/*
 * CD-ROM/DVD Filesystems
 */
#define CONFIG_ISO9660_FS 1
#define CONFIG_JOLIET 1
#define CONFIG_ZISOFS 1
#define CONFIG_ZISOFS_FS 1
#define CONFIG_UDF_FS_MODULE 1
#define CONFIG_UDF_NLS 1

/*
 * DOS/FAT/NT Filesystems
 */
#define CONFIG_FAT_FS_MODULE 1
#define CONFIG_MSDOS_FS_MODULE 1
#define CONFIG_VFAT_FS_MODULE 1
#define CONFIG_FAT_DEFAULT_CODEPAGE 437
#define CONFIG_FAT_DEFAULT_IOCHARSET "ascii"
#undef CONFIG_NTFS_FS

/*
 * Pseudo filesystems
 */
#define CONFIG_PROC_FS 1
#define CONFIG_PROC_KCORE 1
#define CONFIG_SYSFS 1
#undef CONFIG_DEVFS_FS
#define CONFIG_DEVPTS_FS_XATTR 1
#define CONFIG_DEVPTS_FS_SECURITY 1
#define CONFIG_TMPFS 1
#define CONFIG_TMPFS_XATTR 1
#define CONFIG_TMPFS_SECURITY 1
#define CONFIG_HUGETLBFS 1
#define CONFIG_HUGETLB_PAGE 1
#define CONFIG_RAMFS 1

/*
 * Miscellaneous filesystems
 */
#undef CONFIG_ADFS_FS
#undef CONFIG_AFFS_FS
#define CONFIG_HFS_FS_MODULE 1
#define CONFIG_HFSPLUS_FS_MODULE 1
#undef CONFIG_BEFS_FS
#undef CONFIG_BFS_FS
#undef CONFIG_EFS_FS
#undef CONFIG_JFFS_FS
#define CONFIG_JFFS2_FS_MODULE 1
#define CONFIG_JFFS2_FS_DEBUG 0
#define CONFIG_JFFS2_FS_NAND 1
#undef CONFIG_JFFS2_COMPRESSION_OPTIONS
#define CONFIG_JFFS2_ZLIB 1
#define CONFIG_JFFS2_RTIME 1
#undef CONFIG_JFFS2_RUBIN
#define CONFIG_CRAMFS_MODULE 1
#define CONFIG_VXFS_FS_MODULE 1
#undef CONFIG_HPFS_FS
#undef CONFIG_QNX4FS_FS
#undef CONFIG_SYSV_FS
#undef CONFIG_UFS_FS

/*
 * Network File Systems
 */
#define CONFIG_NFS_FS_MODULE 1
#define CONFIG_NFS_V3 1
#define CONFIG_NFS_V4 1
#define CONFIG_NFS_DIRECTIO 1
#define CONFIG_NFSD_MODULE 1
#define CONFIG_NFSD_V3 1
#define CONFIG_NFSD_V4 1
#define CONFIG_NFSD_TCP 1
#define CONFIG_LOCKD_MODULE 1
#define CONFIG_LOCKD_V4 1
#define CONFIG_EXPORTFS_MODULE 1
#define CONFIG_SUNRPC_MODULE 1
#define CONFIG_SUNRPC_GSS_MODULE 1
#define CONFIG_RPCSEC_GSS_KRB5_MODULE 1
#define CONFIG_RPCSEC_GSS_SPKM3_MODULE 1
#define CONFIG_SMB_FS_MODULE 1
#undef CONFIG_SMB_NLS_DEFAULT
#define CONFIG_CIFS_MODULE 1
#undef CONFIG_CIFS_STATS
#define CONFIG_CIFS_XATTR 1
#define CONFIG_CIFS_POSIX 1
#undef CONFIG_NCP_FS
#undef CONFIG_CODA_FS
#undef CONFIG_AFS_FS

/*
 * Partition Types
 */
#define CONFIG_PARTITION_ADVANCED 1
#undef CONFIG_ACORN_PARTITION
#define CONFIG_OSF_PARTITION 1
#undef CONFIG_AMIGA_PARTITION
#undef CONFIG_ATARI_PARTITION
#define CONFIG_MAC_PARTITION 1
#define CONFIG_MSDOS_PARTITION 1
#define CONFIG_BSD_DISKLABEL 1
#define CONFIG_MINIX_SUBPARTITION 1
#define CONFIG_SOLARIS_X86_PARTITION 1
#define CONFIG_UNIXWARE_DISKLABEL 1
#undef CONFIG_LDM_PARTITION
#define CONFIG_SGI_PARTITION 1
#undef CONFIG_ULTRIX_PARTITION
#define CONFIG_SUN_PARTITION 1
#define CONFIG_EFI_PARTITION 1

/*
 * Native Language Support
 */
#define CONFIG_NLS 1
#define CONFIG_NLS_DEFAULT "utf8"
#define CONFIG_NLS_CODEPAGE_437 1
#define CONFIG_NLS_CODEPAGE_737_MODULE 1
#define CONFIG_NLS_CODEPAGE_775_MODULE 1
#define CONFIG_NLS_CODEPAGE_850_MODULE 1
#define CONFIG_NLS_CODEPAGE_852_MODULE 1
#define CONFIG_NLS_CODEPAGE_855_MODULE 1
#define CONFIG_NLS_CODEPAGE_857_MODULE 1
#define CONFIG_NLS_CODEPAGE_860_MODULE 1
#define CONFIG_NLS_CODEPAGE_861_MODULE 1
#define CONFIG_NLS_CODEPAGE_862_MODULE 1
#define CONFIG_NLS_CODEPAGE_863_MODULE 1
#define CONFIG_NLS_CODEPAGE_864_MODULE 1
#define CONFIG_NLS_CODEPAGE_865_MODULE 1
#define CONFIG_NLS_CODEPAGE_866_MODULE 1
#define CONFIG_NLS_CODEPAGE_869_MODULE 1
#define CONFIG_NLS_CODEPAGE_936_MODULE 1
#define CONFIG_NLS_CODEPAGE_950_MODULE 1
#define CONFIG_NLS_CODEPAGE_932_MODULE 1
#define CONFIG_NLS_CODEPAGE_949_MODULE 1
#define CONFIG_NLS_CODEPAGE_874_MODULE 1
#define CONFIG_NLS_ISO8859_8_MODULE 1
#define CONFIG_NLS_CODEPAGE_1250_MODULE 1
#define CONFIG_NLS_CODEPAGE_1251_MODULE 1
#define CONFIG_NLS_ASCII 1
#define CONFIG_NLS_ISO8859_1_MODULE 1
#define CONFIG_NLS_ISO8859_2_MODULE 1
#define CONFIG_NLS_ISO8859_3_MODULE 1
#define CONFIG_NLS_ISO8859_4_MODULE 1
#define CONFIG_NLS_ISO8859_5_MODULE 1
#define CONFIG_NLS_ISO8859_6_MODULE 1
#define CONFIG_NLS_ISO8859_7_MODULE 1
#define CONFIG_NLS_ISO8859_9_MODULE 1
#define CONFIG_NLS_ISO8859_13_MODULE 1
#define CONFIG_NLS_ISO8859_14_MODULE 1
#define CONFIG_NLS_ISO8859_15_MODULE 1
#define CONFIG_NLS_KOI8_R_MODULE 1
#define CONFIG_NLS_KOI8_U_MODULE 1
#define CONFIG_NLS_UTF8_MODULE 1

/*
 * Profiling support
 */
#define CONFIG_PROFILING 1
#define CONFIG_OPROFILE_MODULE 1

/*
 * Kernel hacking
 */
#define CONFIG_DEBUG_KERNEL 1
#define CONFIG_MAGIC_SYSRQ 1
#undef CONFIG_DEBUG_SLAB
#define CONFIG_DEBUG_SPINLOCK 1
#define CONFIG_DEBUG_SPINLOCK_SLEEP 1
#define CONFIG_DEBUG_INFO 1
#undef CONFIG_CHECKING
#define CONFIG_INIT_DEBUG 1
#undef CONFIG_SCHEDSTATS
#undef CONFIG_IOMMU_DEBUG

/*
 * Security options
 */
#define CONFIG_SECURITY 1
#define CONFIG_SECURITY_NETWORK 1
#define CONFIG_SECURITY_CAPABILITIES 1
#undef CONFIG_SECURITY_ROOTPLUG
#define CONFIG_SECURITY_SELINUX 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM 1
#define CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE 1
#define CONFIG_SECURITY_SELINUX_DISABLE 1
#define CONFIG_SECURITY_SELINUX_DEVELOP 1
#define CONFIG_SECURITY_SELINUX_AVC_STATS 1
#undef CONFIG_SECURITY_SELINUX_MLS

/*
 * Cryptographic options
 */
#define CONFIG_CRYPTO 1
#define CONFIG_CRYPTO_HMAC 1
#define CONFIG_CRYPTO_NULL_MODULE 1
#define CONFIG_CRYPTO_MD4_MODULE 1
#define CONFIG_CRYPTO_MD5_MODULE 1
#define CONFIG_CRYPTO_SHA1 1
#define CONFIG_CRYPTO_SHA256_MODULE 1
#define CONFIG_CRYPTO_SHA512_MODULE 1
#define CONFIG_CRYPTO_WP512_MODULE 1
#define CONFIG_CRYPTO_DES_MODULE 1
#define CONFIG_CRYPTO_BLOWFISH_MODULE 1
#define CONFIG_CRYPTO_TWOFISH_MODULE 1
#define CONFIG_CRYPTO_SERPENT_MODULE 1
#define CONFIG_CRYPTO_AES_MODULE 1
#define CONFIG_CRYPTO_CAST5_MODULE 1
#define CONFIG_CRYPTO_CAST6_MODULE 1
#define CONFIG_CRYPTO_TEA_MODULE 1
#define CONFIG_CRYPTO_ARC4_MODULE 1
#define CONFIG_CRYPTO_KHAZAD_MODULE 1
#define CONFIG_CRYPTO_DEFLATE_MODULE 1
#define CONFIG_CRYPTO_MICHAEL_MIC_MODULE 1
#define CONFIG_CRYPTO_CRC32C_MODULE 1
#undef CONFIG_CRYPTO_TEST
#define CONFIG_CRYPTO_SIGNATURE 1
#define CONFIG_CRYPTO_SIGNATURE_DSA 1
#define CONFIG_CRYPTO_MPILIB 1

/*
 * Library routines
 */
#define CONFIG_CRC_CCITT_MODULE 1
#define CONFIG_CRC32 1
#define CONFIG_LIBCRC32C_MODULE 1
#define CONFIG_ZLIB_INFLATE 1
#define CONFIG_ZLIB_DEFLATE_MODULE 1
