export EXTRA_CFLAGS += -D__nocast=
obj-$(CONFIG_INFINIBAND)		+= core/
obj-$(CONFIG_INFINIBAND_MTHCA)		+= hw/mthca/
obj-$(CONFIG_INFINIBAND_IPOIB)		+= ulp/ipoib/
obj-$(CONFIG_INFINIBAND_SDP)		+= ulp/sdp/
obj-$(CONFIG_INFINIBAND_SRP)		+= ulp/srp/
